language: generic
sudo: false

before_install:
  - sudo apt-get -y jq

addons:
  apt:
    update: true

env:
  global:
    - DEV_FINAL_TARGET=docs-final


script:
  - ./scripts/prepare-target.sh $TRAVIS_COMMIT_RANGE
  - ./scripts/publish.sh